name: 快速打包固件

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Get OpenWrt firmware
      id: build
      if: (!cancelled())
      run: |
        [ -d openwrt-armvirt ] || mkdir -p openwrt-armvirt
        curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "ImmortalWrt-N1-.*/immortalwrt-armsr-armv8-generic-rootfs.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
        [ -s DOWNLOAD_ARMVIRT ] && wget -q -P openwrt-armvirt https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMVIRT)

    - name: Package Armvirt as OpenWrt
      uses: v2clash/openwrt_packit@master
      env:
        WHOAMI: v2clash
        OPENWRT_ARMVIRT: openwrt-armvirt/*.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_AUTO_LATEST: true
        KERNEL_REPO_URL: https://github.com/v2clash/build-armbian
        KERNEL_VERSION_NAME: 5.15.y_6.6.y_6.12.y

    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@v1
      with:
        tag: 本地快速打包固件
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GH_TOKEN }}
        body: |
          ### **适用于Amlogic平台OpenWrt固件**
          * **固件信息：**
          默认IP: `192.168.1.4`
          默认用户名: `root`
          默认密码: `password/空`
